import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/components/theme-provider";
import ThemeToggle from "@/components/theme-toggle";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <header className="sticky top-0 z-40 w-full shadow-sm">
            <div className="container flex h-16 items-center space-x-4 sm:justify-between sm:space-x-0">
              <div className="flex items-center gap-6 md:gap-10">
                <nav className="hidden gap-6 md:flex">
                  <Link
                    href="/"
                    className="truncate rounded-full px-4 py-2 transition"
                  >
                    Home
                  </Link>
                  <Link
                    href="/examples"
                    className="truncate rounded-full px-4 py-2 transition"
                  >
                    Examples
                  </Link>
                </nav>
              </div>
              <div className="flex flex-1 items-center justify-end space-x-4">
                <nav className="flex items-center gap-1">
                  <ThemeToggle />
                </nav>
              </div>
            </div>
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
